services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - redis
    ports:
      - "3000:3000"
